#!/bin/bash

docker run \
	--cap-add=NET_ADMIN \
	--hostname=kdc.example.com \
	--privileged \
	--publish-all=true \
	-it \
	-e "container=docker" \
	-v /sys/fs/cgroup:/sys/fs/cgroup \
	geexee/kdc-server 
